# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Theme Settings
theme_settings :
  title : Nayeong's Devlog

  # Profile Settings
  profile :
    image : assets/img/naye0ng.jpeg
    username : Nayeong Kim
    description : "Hi, I'm Nayeong! 
      creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily."

  # Icons
  icons :
    email: "nayeong_e@naver.com" # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: naye0ng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: nayeong_ee

  # Disqus
  disqus_shortname: nayeong-blog

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-bootstrap-sass]
bootstrap:
  assets: true
