# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Theme Settings
theme_settings :
  title : Nayeong's Devlog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/naye0ng_profile.png
    username : Nayeong Kim
    description : "서버와 프론트, 모든 영역에 관심이 많은 주니어 웹 개발자입니다. <br>SSAFY에서 AWS, Django, Vue.js, CSS, SASS를 공부하고 있습니다."
    experience :
      - start : 2017.11.23
        end : 2017.11.24
        experience : NAVER CAMPUS HACK DAY 2017<p style="font-weight:500;font-size:13px;">우수참가자 선정</p>
      - start : 2018.06
        end : 2018.12
        experience : SOFTWARE MAESTRO 9기
      - start : 2018.12 
        end : 
        experience : SSAFY 1기
    skills : 
      - skill : HTML5 & CSS
        value : 85  
      - skill : Javascript & jQuery
        value : 70
      - skill : Python & Django
        value : 65
      - skill : Vue
        value : 65


  # Icons
  icons :
    email: "nayeong_e@naver.com" # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: naye0ng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: nayeong_ee

  # Disqus
  disqus_shortname: nayeong-blog

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: compressed
gems: [jekyll-paginate]
